//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Settings
    {
        public decimal Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<decimal> EmpSerialForDocNotify { get; set; }
        public Nullable<byte> CalcWithGrade { get; set; }
        public Nullable<byte> UseTimeInWorkFlowRequest { get; set; }
        public Nullable<decimal> PerioddayToForwordRequest { get; set; }
        public Nullable<decimal> WorkingHoursPerDay { get; set; }
        public Nullable<byte> ApplyPermissionDiscount { get; set; }
        public Nullable<decimal> PeriodDayToNotifyFinishContract { get; set; }
        public string PayrollDay { get; set; }
        public Nullable<decimal> AllowedPeriodForStopRequestEffect { get; set; }
        public string VacAllownaceBOrA { get; set; }
        public Nullable<byte> chkVacAfterMonth { get; set; }
        public Nullable<byte> chkPaidByLastSal { get; set; }
        public Nullable<byte> chkAbilityTransferVac { get; set; }
        public Nullable<byte> chkAbilityTrncferToNext { get; set; }
        public Nullable<decimal> MaxTrnsferPeriod { get; set; }
        public string VacAllownceSalaryItem { get; set; }
        public string VacTransferAllownceSalaryItem { get; set; }
        public string AbsenceSalaryItem { get; set; }
        public string DelySalaryItem { get; set; }
        public string ExtraSalaryItem { get; set; }
        public string VacTicketHireItem_Id { get; set; }
        public Nullable<decimal> AbsenceCalcWayByDay { get; set; }
    }
}
