//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_Menus
    {
        public decimal Id { get; set; }
        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuNameEn { get; set; }
        public Nullable<int> ParentId { get; set; }
        public byte isActive { get; set; }
        public int LevelId { get; set; }
        public string PathUrl { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string OrderNo { get; set; }
        public decimal idddd { get; set; }
        public string Page_Name { get; set; }
        public string Page_NameEN { get; set; }
    }
}
