//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_ErrorLog
    {
        public decimal Rec_Id { get; set; }
        public string Error_Id { get; set; }
        public string Error_Message { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string ClassName { get; set; }
        public string FunctionName { get; set; }
    }
}
