//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsersMenuPriviledge
    {
        public string UserId { get; set; }
        public string MenuId { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public byte IsVisiable { get; set; }
        public byte CanInsert { get; set; }
        public byte CanUpdate { get; set; }
        public byte CanDelete { get; set; }
        public byte CanSearch { get; set; }
    }
}
