//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public decimal group_ID { get; set; }
        public string Group_Name { get; set; }
        public string Group_NameEN { get; set; }
        public Nullable<byte> Status { get; set; }
        public string User_Role { get; set; }
        public string Description { get; set; }
    }
}
