//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Administrations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hr_Administrations()
        {
            this.Hr_Departments = new HashSet<Hr_Departments>();
        }
    
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Admin_Id { get; set; }
        public string Admin_Code { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_NameEn { get; set; }
        public string Admin_NameConv { get; set; }
        public string Admin_AccountNo { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public string Prefix { get; set; }
        public decimal Id { get; set; }
        public Nullable<byte> IsParent { get; set; }
        public Nullable<byte> HasParent { get; set; }
        public string ParentAdmin_Id { get; set; }
    
        public virtual Hr_Branches Hr_Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_Departments> Hr_Departments { get; set; }
    }
}
