//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Banks
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Bank_Id { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Name_En { get; set; }
        public string Bank_Name_Conv { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Fax { get; set; }
        public string WebSiteUrl { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public string Swift_Code { get; set; }
        public string Country_Id { get; set; }
        public string City_Id { get; set; }
        public string Currency_Id { get; set; }
        public decimal Id { get; set; }
        public string Bank_Code { get; set; }
    }
}
