//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_BranchDocuments
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Doc_Id { get; set; }
        public string Doc_Name { get; set; }
        public string Doc_Name_En { get; set; }
        public string Doc_Name_Conv { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Issue_Place { get; set; }
        public string Issue_Region { get; set; }
        public string Notes { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
    }
}
