//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_BranchAccounts
    {
        public System.Guid DtlHdrId { get; set; }
        public decimal Rec_Id { get; set; }
        public string BranchId { get; set; }
        public string CompanyId { get; set; }
        public string BankId { get; set; }
        public string AccountType { get; set; }
        public string BrnchAccountNo { get; set; }
        public byte Rec_Status { get; set; }
        public string RowState { get; set; }
    }
}
