//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Branch_Docs_Dtls_History
    {
        public System.Guid Dtls_Id { get; set; }
        public Nullable<System.Guid> Hdr_Id { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string FromDateHijri { get; set; }
        public string ToDateHijri { get; set; }
        public decimal ToBeNotifyPeriodBefore { get; set; }
        public Nullable<byte> NotifyPeriodType { get; set; }
        public Nullable<decimal> ResponsibleEmpIdToNotify { get; set; }
        public string NotifyMessage { get; set; }
        public string NotifyMessageEn { get; set; }
        public string ActuallDateNotification { get; set; }
        public string ActuallDateNotificationHijri { get; set; }
        public Nullable<System.Guid> Confirm_NotifyId { get; set; }
        public Nullable<byte> Message_Status { get; set; }
        public string Responsible_Email { get; set; }
        public Nullable<System.DateTime> InsmessageDate { get; set; }
        public Nullable<System.DateTime> UpdStatusDate { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string Issue_Place { get; set; }
        public string Issue_Region { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Branch_Doc_Id { get; set; }
        public string Branch_Doc_Code { get; set; }
        public string Notes { get; set; }
        public string UseNotifyDateType { get; set; }
        public string Doc_Type_Id { get; set; }
        public string DocPath { get; set; }
        public string RegistrationNo { get; set; }
    
        public virtual Hr_Branch_Docs_Dtls_History Hr_Branch_Docs_Dtls_History1 { get; set; }
        public virtual Hr_Branch_Docs_Dtls_History Hr_Branch_Docs_Dtls_History2 { get; set; }
    }
}
