//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_CompaniesTree
    {
        public decimal Rec_Serial_Id { get; set; }
        public string Account_Id { get; set; }
        public string Account_Name { get; set; }
        public string Account_NameEn { get; set; }
        public string Account_NameConv { get; set; }
        public byte Account_Tree_Type { get; set; }
        public string Account_Parent_Id { get; set; }
        public byte HasLastLeaf { get; set; }
        public byte HasLeaf { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
    }
}
