//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Departments
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Dept_Id { get; set; }
        public string Dept_Code { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_NameEn { get; set; }
        public string Dept_NameConv { get; set; }
        public string Dept_AccountNo { get; set; }
        public string Admin_Id { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public string Prefix { get; set; }
        public decimal Id { get; set; }
    
        public virtual Hr_Administrations Hr_Administrations { get; set; }
    }
}
