//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_DailyTimeSheet
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string MonthNo { get; set; }
        public string Transdate { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string DayCode { get; set; }
        public string DayType { get; set; }
        public string Shift_Id { get; set; }
        public string Emp_Check_InTime { get; set; }
        public string Emp_Check_OutTime { get; set; }
        public Nullable<decimal> Working_Hours { get; set; }
        public Nullable<decimal> DelyAmountInMinut { get; set; }
        public Nullable<decimal> ExtraAmountInMinut { get; set; }
        public string ApplyDely { get; set; }
        public string ApplyExtra { get; set; }
        public string ApplyAbsence { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<byte> Confirmed { get; set; }
        public Nullable<decimal> OvertimePeriodFrmRqustInMinute { get; set; }
        public Nullable<decimal> PermissionPeriodFrmRqustInMinute { get; set; }
        public string EmpInVacation { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> DiffDelyInMinut { get; set; }
        public Nullable<decimal> DiffExtraInMinut { get; set; }
    }
}
