//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpAttendance_Hdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hr_EmpAttendance_Hdr()
        {
            this.Hr_EmpAttendance_Dtls = new HashSet<Hr_EmpAttendance_Dtls>();
        }
    
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string Transdate { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string MonthNo { get; set; }
        public Nullable<decimal> DailyWorkingPeriodInMinute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpAttendance_Dtls> Hr_EmpAttendance_Dtls { get; set; }
    }
}
