//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpRequestNotify
    {
        public System.Guid NotifyHdrId { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public System.Guid RequestHdrId { get; set; }
        public string RequestType { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public System.Guid DetailWorkFlowId { get; set; }
        public string Job_Name { get; set; }
        public string Job_NameEn { get; set; }
        public string SenderName { get; set; }
        public string SenderNameEn { get; set; }
        public string CommissionerName { get; set; }
        public string CommissionerNameEn { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<System.DateTime> MaxiumDateReplay { get; set; }
        public Nullable<decimal> Alternate_Emp_Serial_NoNotify { get; set; }
    }
}
