//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpPermission_Settings
    {
        public decimal Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<decimal> AllowedValueInMonthByHour { get; set; }
        public Nullable<decimal> AllowedValueInDayByHour { get; set; }
        public Nullable<decimal> PeriodForDay { get; set; }
        public Nullable<decimal> HourNoForDiscount { get; set; }
        public Nullable<byte> AllowToExceedMonthValue { get; set; }
        public Nullable<byte> AllowToExceedDayValue { get; set; }
        public Nullable<byte> OnlyApplyDiscount { get; set; }
    }
}
