//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpBorrow_Hdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hr_EmpBorrow_Hdr()
        {
            this.Hr_EmpBorrow_Dtls = new HashSet<Hr_EmpBorrow_Dtls>();
        }
    
        public System.Guid Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Rec_No { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string Transdate { get; set; }
        public string Rec_Order_No { get; set; }
        public Nullable<System.Guid> Rec_Order_HdrId { get; set; }
        public string Request_Id { get; set; }
        public decimal Borrow_Value { get; set; }
        public decimal Borrow_Period { get; set; }
        public string BorrowStartDate { get; set; }
        public Nullable<decimal> Borrow_MonthValue { get; set; }
        public byte Borrow_Status { get; set; }
        public string Notes { get; set; }
        public string HireItem_Id { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DocumentPath { get; set; }
        public decimal Commissioner_Serial_no { get; set; }
        public string BorrowDuesDate { get; set; }
        public string MessageNotesForEmp { get; set; }
        public Nullable<decimal> Contract_Id { get; set; }
        public Nullable<decimal> ContractPeriod_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpBorrow_Dtls> Hr_EmpBorrow_Dtls { get; set; }
    }
}
