//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpSpouses
    {
        public System.Guid Dtls_Id { get; set; }
        public decimal Rec_id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string SpouseNameArabic { get; set; }
        public string SpouseNameEn { get; set; }
        public string SpouseNameConv { get; set; }
        public string SpouseBithDate { get; set; }
        public string MarriedDate { get; set; }
        public string SpouseNationality_Id { get; set; }
        public string SpousePassportNo { get; set; }
        public string SpousePassportIssueDate { get; set; }
        public string SpousePassportExpiryDate { get; set; }
        public string SpouseInsuranceNo { get; set; }
        public string SpouseInsuranceIssueDate { get; set; }
        public string SpouseInsuranceExpiryDate { get; set; }
        public string National_Id { get; set; }
        public string NationalStartDate { get; set; }
        public string NationalEndDate { get; set; }
        public string MarriedContractAttach { get; set; }
        public string SpouseNotes { get; set; }
        public Nullable<decimal> Emp_Serial_No { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Rec_Status { get; set; }
        public string RowState { get; set; }
    }
}
