//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpDues
    {
        public decimal Rec_id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string GradeJob_Id { get; set; }
        public string Grade_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string HireItem_Id { get; set; }
        public decimal HireItem_Value { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public byte Rec_Status { get; set; }
        public string RowState { get; set; }
    }
}
