//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpExperiences
    {
        public System.Guid Dtls_Id { get; set; }
        public decimal Rec_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string Experience_Name { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Job_Title { get; set; }
        public string Place { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Notes { get; set; }
        public string DocAttach { get; set; }
        public string ExperienceCategory_Id { get; set; }
        public string Experience_Id { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
    
        public virtual Hr_Employees Hr_Employees { get; set; }
    }
}
