//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpDuesVactionTicketHistory
    {
        public decimal Dtls_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string GradeJob_Id { get; set; }
        public string GradeJob_IdNew { get; set; }
        public Nullable<decimal> VactionPeriod { get; set; }
        public Nullable<decimal> VactionPeriodNew { get; set; }
        public string VactionTicketType { get; set; }
        public string VactionTicketTypeNew { get; set; }
        public string InternationalWorkTicketType { get; set; }
        public string InternationalWorkTicketTypeNew { get; set; }
        public string LocalWorkTicketType { get; set; }
        public string LocalWorkTicketTypeNew { get; set; }
        public string TransDate { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public string InsTransUser { get; set; }
        public Nullable<System.DateTime> InsTransDate { get; set; }
        public Nullable<decimal> Dtls_Id_Org { get; set; }
        public Nullable<byte> RecStatus { get; set; }
        public Nullable<decimal> WorkingMonthNo { get; set; }
        public string WorkingPeriodType { get; set; }
        public Nullable<decimal> WorkingMonthNoNew { get; set; }
        public string WorkingPeriodTypeNew { get; set; }
    }
}
