//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmploymentExperinceRecord
    {
        public System.Guid Dtls_Id { get; set; }
        public decimal Rec_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Experience_Id { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<System.Guid> Rec_Hdr_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<int> RowId { get; set; }
    }
}
