//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Emp_HiringMonthStatus
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Id { get; set; }
        public string MonthNo { get; set; }
        public Nullable<byte> PreparedIsDone { get; set; }
        public Nullable<byte> AdoptedIsDone { get; set; }
    }
}
