//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Emp_Doc_Notification_Dtls
    {
        public decimal NotifyRec_Hdr_Id { get; set; }
        public System.Guid Confirm_NotifyId { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public System.Guid EmpDocDtls_Id { get; set; }
        public Nullable<byte> Message_Status { get; set; }
        public string Responsible_Email { get; set; }
        public Nullable<decimal> EmpSerialNo { get; set; }
        public string NotifyMessage { get; set; }
        public string NotifyMessageEn { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<decimal> OwnerEmpDoc { get; set; }
        public string Doc_Type_Id { get; set; }
        public string RoleType { get; set; }
    }
}
