//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpAttendance_Dtls
    {
        public System.Guid Dtls_Id { get; set; }
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Emp_Check_InTime { get; set; }
        public string Shift_FromTime { get; set; }
        public string Shift_ToTime { get; set; }
        public string Emp_Check_OutTime { get; set; }
        public string Shift_Id { get; set; }
        public string BeforeCheck_In { get; set; }
        public Nullable<decimal> BeforeCheck_In_EffectInMin { get; set; }
        public string AfterCheck_In { get; set; }
        public Nullable<decimal> AfterCheck_In_EffectInMin { get; set; }
        public string BeforeCheck_OUT { get; set; }
        public Nullable<decimal> BeforeCheck_OUT_EffectInMin { get; set; }
        public string AfterCheck__OUT { get; set; }
        public Nullable<decimal> AfterCheck__OUT_EffectInMin { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> WorkingPeriodWithShftInMinute { get; set; }
    
        public virtual Hr_EmpAttendance_Hdr Hr_EmpAttendance_Hdr { get; set; }
    }
}
