//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmployeeContractPeriods_History
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Row_id { get; set; }
        public decimal ContractPeriod_Id { get; set; }
        public Nullable<decimal> Contract_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public Nullable<decimal> NoOfRestVacDays { get; set; }
        public Nullable<decimal> NoOfRestVacDaysNew { get; set; }
        public Nullable<System.Guid> LastTransRec_hdr_Id { get; set; }
        public Nullable<System.Guid> LastTransRec_hdr_IdNew { get; set; }
        public Nullable<System.DateTime> Insdate { get; set; }
    }
}
