//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Emp_Docs_Hdr
    {
        public System.Guid Hdr_Id { get; set; }
        public decimal Emp_Doc_Id { get; set; }
        public string Emp_Doc_Code { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Doc_Type_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string LastFromDate { get; set; }
        public string LastToDate { get; set; }
        public string LastFromDateHijri { get; set; }
        public string LastToDateHijri { get; set; }
        public decimal ToBeNotifyPeriodBefore { get; set; }
        public byte NotifyPeriodType { get; set; }
        public Nullable<decimal> ResponsibleEmpIdToNotify { get; set; }
        public string NotifyMessage { get; set; }
        public string NotifyMessageEn { get; set; }
        public string ActuallDateNotification { get; set; }
        public string ActuallDateNotificationHijri { get; set; }
        public byte UseNotifyDateType { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string Issue_Place { get; set; }
        public string Issue_Region { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Rec_Status { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Notes { get; set; }
        public string DocPath { get; set; }
        public byte SendNotify { get; set; }
        public string RegistrationNo { get; set; }
        public string DocOwnerName { get; set; }
    
        public virtual Hr_DocumentTypes Hr_DocumentTypes { get; set; }
        public virtual Hr_Employees Hr_Employees { get; set; }
    }
}
