//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hr_Employees()
        {
            this.Hr_Emp_Assets = new HashSet<Hr_Emp_Assets>();
            this.Hr_Emp_Docs_Hdr = new HashSet<Hr_Emp_Docs_Hdr>();
            this.Hr_EmpAbsenceRecord = new HashSet<Hr_EmpAbsenceRecord>();
            this.Hr_EmpAnnualLeavePlanRecord = new HashSet<Hr_EmpAnnualLeavePlanRecord>();
            this.Hr_EmpAnnualLeavePlanRequest = new HashSet<Hr_EmpAnnualLeavePlanRequest>();
            this.Hr_EmpBorrowDelayRecord = new HashSet<Hr_EmpBorrowDelayRecord>();
            this.Hr_EmpBorrowDelayRequest = new HashSet<Hr_EmpBorrowDelayRequest>();
            this.Hr_EmpBorrowRequest = new HashSet<Hr_EmpBorrowRequest>();
            this.Hr_EmpCertifications = new HashSet<Hr_EmpCertifications>();
            this.Hr_EmpDelayRecord = new HashSet<Hr_EmpDelayRecord>();
            this.Hr_EmpDisciplinaryProcedureRecord = new HashSet<Hr_EmpDisciplinaryProcedureRecord>();
            this.Hr_EmpDisciplinaryProcedureRequest = new HashSet<Hr_EmpDisciplinaryProcedureRequest>();
            this.Hr_EmpDismissalRecord = new HashSet<Hr_EmpDismissalRecord>();
            this.Hr_EmpDismissalRequest = new HashSet<Hr_EmpDismissalRequest>();
            this.Hr_EmpEmploymentRecord = new HashSet<Hr_EmpEmploymentRecord>();
            this.Hr_EmpEmploymentRequest = new HashSet<Hr_EmpEmploymentRequest>();
            this.Hr_EmpExperiences = new HashSet<Hr_EmpExperiences>();
            this.Hr_EmpExtraRecord = new HashSet<Hr_EmpExtraRecord>();
            this.Hr_EmpJobMissionRecord = new HashSet<Hr_EmpJobMissionRecord>();
            this.Hr_EmpJobMissionRequest = new HashSet<Hr_EmpJobMissionRequest>();
            this.Hr_EmpOtherMonthlyValueRecord = new HashSet<Hr_EmpOtherMonthlyValueRecord>();
            this.Hr_EmpOverTimeOrder = new HashSet<Hr_EmpOverTimeOrder>();
            this.Hr_EmpOverTimeRecord = new HashSet<Hr_EmpOverTimeRecord>();
            this.Hr_EmpOverTimeRequest = new HashSet<Hr_EmpOverTimeRequest>();
            this.Hr_EmpPermissionOrder = new HashSet<Hr_EmpPermissionOrder>();
            this.Hr_EmpPermissionRecord = new HashSet<Hr_EmpPermissionRecord>();
            this.Hr_EmpPermissionRequest = new HashSet<Hr_EmpPermissionRequest>();
            this.Hr_EmpQualifications = new HashSet<Hr_EmpQualifications>();
            this.Hr_EmpResignationRecord = new HashSet<Hr_EmpResignationRecord>();
            this.Hr_EmpResignationRequest = new HashSet<Hr_EmpResignationRequest>();
            this.Hr_EmpRewardRecord = new HashSet<Hr_EmpRewardRecord>();
            this.Hr_EmpRewardRequest = new HashSet<Hr_EmpRewardRequest>();
            this.Hr_EmpSecondmentRecord = new HashSet<Hr_EmpSecondmentRecord>();
            this.Hr_EmpSecondmentRequest = new HashSet<Hr_EmpSecondmentRequest>();
            this.Hr_EmpSkills = new HashSet<Hr_EmpSkills>();
            this.Hr_EmpTransferEmployeeRecord = new HashSet<Hr_EmpTransferEmployeeRecord>();
            this.Hr_EmpTransferEmployeeRequest = new HashSet<Hr_EmpTransferEmployeeRequest>();
            this.Hr_EmpTravelTickectRecord = new HashSet<Hr_EmpTravelTickectRecord>();
            this.Hr_EmpTravelTickectRequest = new HashSet<Hr_EmpTravelTickectRequest>();
            this.Hr_EmpVactionOrder = new HashSet<Hr_EmpVactionOrder>();
            this.Hr_EmpVactionRecord = new HashSet<Hr_EmpVactionRecord>();
            this.Hr_EmpVactionRequest = new HashSet<Hr_EmpVactionRequest>();
        }
    
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string Emp_First_Name { get; set; }
        public string Emp_Meduim_Name { get; set; }
        public string Emp_GrandFatherName { get; set; }
        public string Emp_Last_Name { get; set; }
        public string Emp_First_NameEn { get; set; }
        public string Emp_Meduim_NameEn { get; set; }
        public string Emp_GrandFatherNameEn { get; set; }
        public string Emp_Last_NameEn { get; set; }
        public string Emp_Last_NameConv { get; set; }
        public string Birth_Date { get; set; }
        public string Birth_Place { get; set; }
        public string Hire_Date { get; set; }
        public string Social_Status_Id { get; set; }
        public string Military_Status_Id { get; set; }
        public string Geneder_Id { get; set; }
        public string Religion_Id { get; set; }
        public string Countery_Id { get; set; }
        public string City_Id { get; set; }
        public string Nationality_Id { get; set; }
        public string Project_Id { get; set; }
        public string Contract_Id { get; set; }
        public string Admin_Id { get; set; }
        public string Dept_Id { get; set; }
        public string Job_Id { get; set; }
        public string JobTitle { get; set; }
        public string Grade_Id { get; set; }
        public string Qualify_Type_Id { get; set; }
        public string Qualify_Id { get; set; }
        public string Shift_Id { get; set; }
        public string Identity_Type_Id { get; set; }
        public string Identity_No { get; set; }
        public string Identity_StartDate { get; set; }
        public string Identity_StartDateHijri { get; set; }
        public string Identity_EndDate { get; set; }
        public string Identity_EndDateHijri { get; set; }
        public string Inside_Phone { get; set; }
        public string Inside_Mobile1 { get; set; }
        public string Inside_Mobile2 { get; set; }
        public string Outside_Phone1 { get; set; }
        public string Outside_Mobile1 { get; set; }
        public string Outside_Mobile2 { get; set; }
        public string Fax { get; set; }
        public string InsideAddress1 { get; set; }
        public string InsideAddress2 { get; set; }
        public string OutsideAddress1 { get; set; }
        public string OutsideAddress2 { get; set; }
        public string BusinessEmail { get; set; }
        public string PrivateEmail { get; set; }
        public string Manager_Id { get; set; }
        public string Bank_No1 { get; set; }
        public string AccountBankNo1 { get; set; }
        public string IBAN_No1 { get; set; }
        public string Bank_No2 { get; set; }
        public string AccountBankNo2 { get; set; }
        public string IBAN_No2 { get; set; }
        public Nullable<byte> HasFingerPrint { get; set; }
        public Nullable<byte> HasAbsence { get; set; }
        public Nullable<byte> HasOverTime { get; set; }
        public Nullable<byte> HasDelay { get; set; }
        public Nullable<byte> HasPermission { get; set; }
        public Nullable<byte> HasMedicalInsurance { get; set; }
        public string Medical_Insurance_No { get; set; }
        public string Medical_Insurance_StartDate { get; set; }
        public string Medical_Insurance_StartDateHijri { get; set; }
        public string Medical_Insurance_EndDate { get; set; }
        public string Medical_Insurance_EndDateHijri { get; set; }
        public string Social_Insurance_No { get; set; }
        public string Notes { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public string Prefix { get; set; }
        public string FullNameArabic { get; set; }
        public string FullNameEn { get; set; }
        public string ImagePath { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssueDate { get; set; }
        public string PassportExpiryDate { get; set; }
        public Nullable<byte> IsCommissioner { get; set; }
        public Nullable<decimal> Commissioner_Serial_no { get; set; }
        public Nullable<byte> NeedMandate { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public string GradeJob_Id { get; set; }
        public string EmpStatusId { get; set; }
        public Nullable<byte> HasManager { get; set; }
        public string ContractClassify { get; set; }
        public string StartContract { get; set; }
        public string EndContract { get; set; }
        public Nullable<decimal> ContractPeriodByMonth { get; set; }
        public Nullable<byte> IsEmpManager { get; set; }
        public string WorkStartingDate { get; set; }
        public string WorkStartingDateAfterRenwal { get; set; }
        public Nullable<byte> DeductInsurance { get; set; }
        public string EnrollFPNumber { get; set; }
        public string Attendance_Type { get; set; }
        public string DeliverSalType { get; set; }
    
        public virtual Hr_Branches Hr_Branches { get; set; }
        public virtual Hr_Companies Hr_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_Emp_Assets> Hr_Emp_Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_Emp_Docs_Hdr> Hr_Emp_Docs_Hdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpAbsenceRecord> Hr_EmpAbsenceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpAnnualLeavePlanRecord> Hr_EmpAnnualLeavePlanRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpAnnualLeavePlanRequest> Hr_EmpAnnualLeavePlanRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpBorrowDelayRecord> Hr_EmpBorrowDelayRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpBorrowDelayRequest> Hr_EmpBorrowDelayRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpBorrowRequest> Hr_EmpBorrowRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpCertifications> Hr_EmpCertifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpDelayRecord> Hr_EmpDelayRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpDisciplinaryProcedureRecord> Hr_EmpDisciplinaryProcedureRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpDisciplinaryProcedureRequest> Hr_EmpDisciplinaryProcedureRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpDismissalRecord> Hr_EmpDismissalRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpDismissalRequest> Hr_EmpDismissalRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpEmploymentRecord> Hr_EmpEmploymentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpEmploymentRequest> Hr_EmpEmploymentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpExperiences> Hr_EmpExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpExtraRecord> Hr_EmpExtraRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpJobMissionRecord> Hr_EmpJobMissionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpJobMissionRequest> Hr_EmpJobMissionRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpOtherMonthlyValueRecord> Hr_EmpOtherMonthlyValueRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpOverTimeOrder> Hr_EmpOverTimeOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpOverTimeRecord> Hr_EmpOverTimeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpOverTimeRequest> Hr_EmpOverTimeRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpPermissionOrder> Hr_EmpPermissionOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpPermissionRecord> Hr_EmpPermissionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpPermissionRequest> Hr_EmpPermissionRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpQualifications> Hr_EmpQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpResignationRecord> Hr_EmpResignationRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpResignationRequest> Hr_EmpResignationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpRewardRecord> Hr_EmpRewardRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpRewardRequest> Hr_EmpRewardRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpSecondmentRecord> Hr_EmpSecondmentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpSecondmentRequest> Hr_EmpSecondmentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpSkills> Hr_EmpSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpTransferEmployeeRecord> Hr_EmpTransferEmployeeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpTransferEmployeeRequest> Hr_EmpTransferEmployeeRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpTravelTickectRecord> Hr_EmpTravelTickectRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpTravelTickectRequest> Hr_EmpTravelTickectRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpVactionOrder> Hr_EmpVactionOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpVactionRecord> Hr_EmpVactionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hr_EmpVactionRequest> Hr_EmpVactionRequest { get; set; }
    }
}
