//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpVactionOrder_History
    {
        public System.Guid Hdr_Id { get; set; }
        public decimal Rec_No { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public decimal Order_No { get; set; }
        public byte Order_Status { get; set; }
        public string UserName { get; set; }
        public string UserComment { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
    }
}
