//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmployeesHistory
    {
        public decimal RecId { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<decimal> Emp_Serial_No { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string Project_Id { get; set; }
        public string Project_IdNew { get; set; }
        public string Contract_Id { get; set; }
        public string Contract_IdNew { get; set; }
        public string Admin_Id { get; set; }
        public string Admin_IdNew { get; set; }
        public string Dept_Id { get; set; }
        public string Dept_IdNew { get; set; }
        public string Job_Id { get; set; }
        public string Job_IdNew { get; set; }
        public string Grade_Id { get; set; }
        public string Grade_IdNew { get; set; }
        public string JobTitle { get; set; }
        public string JobTitleNew { get; set; }
        public string GradeJob_Id { get; set; }
        public string GradeJob_IdNew { get; set; }
        public string Qualify_Type_Id { get; set; }
        public string Qualify_Type_IdNew { get; set; }
        public string Qualify_Id { get; set; }
        public string Qualify_IdNew { get; set; }
        public string Shift_Id { get; set; }
        public string Shift_IdNew { get; set; }
        public string Manager_Id { get; set; }
        public string Manager_IdNew { get; set; }
        public Nullable<decimal> Commissioner_Serial_no { get; set; }
        public Nullable<decimal> Commissioner_Serial_noNew { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string InsTransUser { get; set; }
        public Nullable<System.DateTime> InsTransDate { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public string Transdate { get; set; }
        public Nullable<byte> Rec_Status { get; set; }
        public Nullable<byte> Rec_StatusNew { get; set; }
        public string EmpStatusId { get; set; }
        public string EmpStatusIdNew { get; set; }
        public string ContractClassify { get; set; }
        public string ContractClassifyNew { get; set; }
        public string StartContract { get; set; }
        public string StartContractNew { get; set; }
        public string EndContract { get; set; }
        public string EndContractNew { get; set; }
        public Nullable<decimal> ContractPeriodByMonth { get; set; }
        public Nullable<decimal> ContractPeriodByMonthNew { get; set; }
    }
}
