//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpSons
    {
        public System.Guid Dtls_Id { get; set; }
        public decimal Rec_id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string SonNameArabic { get; set; }
        public string SonNameEn { get; set; }
        public string SonNameConv { get; set; }
        public string SonBithDate { get; set; }
        public string DeathDate { get; set; }
        public string SonNationality_Id { get; set; }
        public string SonPassportNo { get; set; }
        public string SonPassportIssueDate { get; set; }
        public string SonPassportExpiryDate { get; set; }
        public string SonInsuranceNo { get; set; }
        public string SonInsuranceIssueDate { get; set; }
        public string SonInsuranceExpiryDate { get; set; }
        public string National_Id { get; set; }
        public string NationalStartDate { get; set; }
        public string NationalEndDate { get; set; }
        public string BirthCertificateAttach { get; set; }
        public string SonNotes { get; set; }
        public Nullable<decimal> Emp_Serial_No { get; set; }
        public Nullable<System.Guid> EmpHdrId { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Rec_Status { get; set; }
        public string RowState { get; set; }
        public string SonGeneder_Id { get; set; }
        public string SonSocial_Status_Id { get; set; }
        public string SonQualify_Id { get; set; }
        public string SonImageAttach { get; set; }
    }
}
