//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpVactionRequestWorkFlow
    {
        public System.Guid DtlsID { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<System.Guid> Hdr_Id { get; set; }
        public string RequestType { get; set; }
        public string ReferenceNo { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string Job_Id { get; set; }
        public byte WorkFlowOrder { get; set; }
        public byte EmpReplay { get; set; }
        public string RequestStatus { get; set; }
        public string EmpComment { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string EmpNameReplay { get; set; }
        public Nullable<System.DateTime> DateReplay { get; set; }
        public Nullable<System.DateTime> MaxiumDateReplay { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Alternate_Emp_Serial_No { get; set; }
        public string Alternate_Job_Id { get; set; }
    }
}
