//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpVactionRecord
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public decimal Rec_No { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public Nullable<System.Guid> Rec_Order_HdrId { get; set; }
        public string Rec_Order_No { get; set; }
        public string Request_Id { get; set; }
        public string TransDate { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string BackDate { get; set; }
        public decimal Vaction_Period { get; set; }
        public string PlaceOfResidence { get; set; }
        public string DocumentPath { get; set; }
        public decimal Commissioner_Serial_no { get; set; }
        public string Reason { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string MessageNotesForEmp { get; set; }
        public string HireItem_Id { get; set; }
        public Nullable<decimal> FreeBalancRequest { get; set; }
        public Nullable<decimal> ChargeBalancRequest { get; set; }
        public string AcuallBackDate { get; set; }
        public Nullable<decimal> AcuallVaction_Peiod { get; set; }
        public Nullable<decimal> Contract_Id { get; set; }
        public Nullable<decimal> ContractPeriod_Id { get; set; }
        public Nullable<decimal> Tot_Transferd_Period { get; set; }
        public Nullable<decimal> Curr_DiscVac_Period { get; set; }
        public Nullable<decimal> Curr_DiscTransferd_Period { get; set; }
        public Nullable<decimal> Prev_Vaction_Period { get; set; }
        public Nullable<decimal> CurrAllowedVacTillDate { get; set; }
        public string Vac_Place_Type { get; set; }
        public Nullable<decimal> Offical_Vaction_Period { get; set; }
        public Nullable<decimal> VactionFromPrmEffec { get; set; }
    
        public virtual Hr_Employees Hr_Employees { get; set; }
    }
}
