//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_FinalFingerPrint
    {
        public System.Guid Rec_Id { get; set; }
        public string IRow { get; set; }
        public string TMachineNumber { get; set; }
        public string EnrollNumber { get; set; }
        public string VerifyMode { get; set; }
        public string InOutMode { get; set; }
        public string DateTimeEnroll { get; set; }
        public string MonthYearNo { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string YearNo { get; set; }
        public string MonthNo { get; set; }
        public string DayNo { get; set; }
        public string HourNo { get; set; }
        public string MinuteNo { get; set; }
        public Nullable<byte> Processed { get; set; }
        public Nullable<byte> DataInputType { get; set; }
        public Nullable<byte> UpdateFPStatus { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
