//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_GradeHiringItemFixed
    {
        public decimal Dtls_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string GradeJob_Id { get; set; }
        public string HireItem_Id { get; set; }
        public byte HireItem_Value_Type { get; set; }
        public decimal HireItem_Value { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
    }
}
