//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_HiringEmpReceivableDues_Dtls
    {
        public System.Guid Dtls_Id { get; set; }
        public System.Guid Hdr_Id { get; set; }
        public string HireItem_Id { get; set; }
        public decimal HireItem_Value { get; set; }
        public string TransItemDate { get; set; }
        public string DueDate { get; set; }
        public string InsItemUser { get; set; }
        public Nullable<System.DateTime> InsItemDate { get; set; }
        public Nullable<byte> Confirmed { get; set; }
        public Nullable<System.Guid> RecEmpDuesHdr_Id { get; set; }
        public Nullable<System.Guid> RecRequestHdr_Id { get; set; }
        public Nullable<System.DateTime> ConfirmedUpdateDate { get; set; }
        public string ConfirmDate { get; set; }
    
        public virtual Hr_HiringEmpReceivableDues_Hdr Hr_HiringEmpReceivableDues_Hdr { get; set; }
    }
}
