//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_HiringMonth_FollowUp_Dtls
    {
        public System.Guid Dtls_Id { get; set; }
        public System.Guid RecHdr_Id { get; set; }
        public string HireItem_Id { get; set; }
        public byte HireItem_Type { get; set; }
        public decimal HireItem_Value { get; set; }
        public decimal HireItem_ActuallValue { get; set; }
        public decimal HireItem_DiffValue { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> RecEmpDuesHdr_Id { get; set; }
        public Nullable<System.Guid> RecRequestHdr_Id { get; set; }
    
        public virtual Hr_HiringMonth_FollowUp_Hdr Hr_HiringMonth_FollowUp_Hdr { get; set; }
    }
}
