//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_HiringEmpDuesRequestEffect
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<decimal> Emp_Serial_No { get; set; }
        public string Month_No { get; set; }
        public string TransDate { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<System.Guid> Request_Hdr_Id { get; set; }
        public string HireItem_Id { get; set; }
        public Nullable<byte> HireItem_Type { get; set; }
        public Nullable<decimal> HireItem_Value { get; set; }
        public Nullable<System.Guid> Request_Dtls_Id { get; set; }
    }
}
