//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_InporgressAndApprovedRequests
    {
        public decimal Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public System.Guid Rec_Hdr_Id { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Order_Status { get; set; }
        public string RequestGroupType_Id { get; set; }
        public string RequestId { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
    }
}
