//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Jobs
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Job_Id { get; set; }
        public string Job_Code { get; set; }
        public string Job_Name { get; set; }
        public string Job_NameEn { get; set; }
        public string Job_NameConv { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public byte IsManager { get; set; }
        public string GradeJob_Id { get; set; }
        public decimal Id { get; set; }
    }
}
