//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Notification_Types
    {
        public string NotificationType_Id { get; set; }
        public string NotificationType_Name { get; set; }
        public string NotificationType_NameEn { get; set; }
        public byte Rec_Status { get; set; }
    }
}
