//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_RequestTypesDtls
    {
        public decimal DtlsId { get; set; }
        public string RequestTypeId { get; set; }
        public decimal RequestTypeValue { get; set; }
        public string RequestDiscountType { get; set; }
        public decimal RequestRatioValue { get; set; }
        public string ValueType { get; set; }
    }
}
