//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_RequestTypes
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Request_Id { get; set; }
        public string Request_Name { get; set; }
        public string Request_NameEn { get; set; }
        public string Request_NameConv { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte Rec_Status { get; set; }
        public string Prefix { get; set; }
        public Nullable<byte> RequestType { get; set; }
        public byte AttachIsNecessary { get; set; }
        public byte VactionIndivisible { get; set; }
        public byte SendOnlyToManger { get; set; }
        public Nullable<byte> ChkJoinHireItem { get; set; }
        public string HireItem_Id { get; set; }
    }
}
