//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Shifts_Details
    {
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public System.Guid Dtls_Id { get; set; }
        public string Shift_Id { get; set; }
        public string Period_no { get; set; }
        public string Period_Name { get; set; }
        public string From_Time { get; set; }
        public string To_Time { get; set; }
    }
}
