//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Social_InsuranceDeductionPercntg_SA
    {
        public decimal Rec_Id { get; set; }
        public string Insurance_Type_Id { get; set; }
        public string HireItem_Id { get; set; }
        public Nullable<byte> DeductOnEmpOrComp { get; set; }
        public Nullable<byte> EmpNational_TypeId { get; set; }
        public Nullable<decimal> DeductPercentage { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
    }
}
