//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_TimeAttendanceSetting
    {
        public decimal Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Machine_No { get; set; }
        public Nullable<byte> Check_In_CodeFrmFP { get; set; }
        public Nullable<byte> Check_Out_CodeFrmFP { get; set; }
    }
}
