//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_WeekSysDays
    {
        public string WeekSysDayId { get; set; }
        public string WeekSysDayName { get; set; }
        public string WeekSysDayNameEn { get; set; }
        public string ShortName { get; set; }
        public string DayFirstInSqlCode { get; set; }
    }
}
