//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_WeekPolicySystem
    {
        public decimal id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public System.Guid PolicyId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyNameEn { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> WeekDays { get; set; }
        public Nullable<decimal> WeekStartOn { get; set; }
        public string PartialDayBeginTime { get; set; }
        public string PartialDayEndTime { get; set; }
        public Nullable<decimal> PDDuration { get; set; }
        public Nullable<decimal> MinMinuteWorkingFromWeekOff { get; set; }
        public Nullable<decimal> CalcHalfDayIfWorkingUpTo { get; set; }
        public Nullable<decimal> CalcFullDayIfWorkingexceedsTo { get; set; }
        public Nullable<decimal> AllowedPeriodSysToCalcByMin { get; set; }
        public Nullable<decimal> FirstFPBeforeShiftByMin { get; set; }
        public Nullable<decimal> LastFPAfterShiftByMin { get; set; }
    }
}
