//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxtEmployeeData
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Identity_Id { get; set; }
        public string Finish_Date__AM_ { get; set; }
        public string Finish_Date_Hijri { get; set; }
        public string Job_ { get; set; }
        public string Status { get; set; }
        public string year { get; set; }
        public string vacation_days { get; set; }
        public decimal id { get; set; }
    }
}
